//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ApiSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ApiSettings defaultInstance = ((ApiSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ApiSettings())));
        
        public static ApiSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.openweathermap.org/data/2.5/weather?q=Santo%20Domingo,%20DO&units=met" +
            "ric&lang=es&appid=7044b761a2ff327d5116dc33adef18ed")]
        public string Url {
            get {
                return ((string)(this["Url"]));
            }
        }
    }
}
